# На каком порту стартует приложение
server:
    port: 8082

# Настройки логирования
logging:
    level:
        com.example.bank_api: debug
    file:
        name: logs/app_debug.log

# Настройки БД
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:15432/postgres
        username: sa
        password: 12345
    jpa:
        show-sql: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    h2:
        console:
            enabled: true # web-консоль по адресу: /h2-console
            settings:
                web-allow-others: false
